### ISSUE TITLE
Bug: `--testflight` flag for `app-store-connect publish` action has misleading documentation

### ISSUE THREAD

**Issue by helinanever** [codemagic-ci-cd/cli-tools#109]
The following comment in current documentation in https://github.com/codemagic-ci-cd/cli-tools/blob/master/docs/app-store-connect/publish.md is inaccurate as it's not possible to submit an app to external testers. Using this flag only makes the build available to internal testers.

```
-t, --testflight
Submit an app for Testflight beta app review to allow external testing
```

**Comment by priitlatt** [comment]
@helinanever, could you please propose a better alternative for the description?

**Comment by priitlatt** [comment]
Taking most recent changes into account, is it still an issue?

**Comment by helinanever** [comment]
Noy anymore, closing.
