### ISSUE TITLE
Do not create keychains to temporary directory by default

### ISSUE THREAD

**Issue by craastad** [codemagic-ci-cd/cli-tools#126]
Naively using CLI tools can have undesirable consequences for the mac keychain. We should work to avoid these for default usages.

My mistake was fixed with `keychain make-default ~/Library/Keychains/login.keychain-db`

> I think that maybe we shouldn’t generate the keychain into $TMPDIR directory by default. when default keychain is not restored back to the system default login keychain and a reboot is performed, then the previous default keychain goes missing and system OS finds itself in a odd situation where default keychain is set, but it doesn’t exist.

The code changes are drafted in: https://github.com/codemagic-ci-cd/cli-tools/pull/125/files

**Comment by priitlatt** [comment]
Currently [`keychain initialize`](https://github.com/codemagic-ci-cd/cli-tools/blob/master/docs/keychain/initialize.md) indeed creates new keychain into a temporary directory by default. This can cause issues if system is rebooted and login keychain is not set to default beforehand.
