### ISSUE TITLE
Update docs about CLI options that can be defined using files or environment variables

### ISSUE THREAD

**Issue by helinanever** [codemagic-ci-cd/cli-tools#127]
In the description for `--beta-build-localizations=BETA_BUILD_LOCALIZATIONS` in`docs/app-store-connect/publish.md`, minor text edits are required. Here's the edited version:
>Localized beta test info for what's new in the uploaded build as a JSON encoded list. For example, `[{"locale": "en-US", "whats_new": "What's new in English"}]`. See `--locale` for possible locale options. If not given, the value will be checked from the environment variable `APP_STORE_CONNECT_BETA_BUILD_LOCALIZATIONS`. Alternatively to entering ` BETA_BUILD_LOCALIZATIONS` in plaintext, it may also be specified using the `@env:` prefix followed by an environment variable name, or the `@file:` prefix followed by a path to the file containing the value. Example: `@env:<variable>` uses the value in the environment variable named `<variable>`, and `@file:<file_path>` uses the value from file at `<file_path>`.

Link to diff: https://github.com/codemagic-ci-cd/cli-tools/pull/124/files#r660574082

**Comment by priitlatt** [comment]
The description generated by [`EnvironmentArgumentValue. get_description`](https://github.com/codemagic-ci-cd/cli-tools/blob/e1d73613c7b3f9c8b8577af8649b7634e291e6d1/src/codemagic/cli/argument/typed_cli_argument.py#L132) contains some typos and needs to be revised. Original [comment](https://github.com/codemagic-ci-cd/cli-tools/pull/124#pullrequestreview-694976615) was left on PR #124, but it is applicable to all arguments that can be read from files or environment.
