### ISSUE TITLE
DOCS default value for --pre-release-version=PRE_RELEASE_VERSION is missing

### ISSUE THREAD

**Issue by martinjeret** [codemagic-ci-cd/cli-tools#137]
It would be good to document what build number are we fetching or what is the default value for

```
app-store-connect get-latest-testflight-build-number --pre-release-version=PRE_RELEASE_VERSION
```

Users sometimes get unexpected result from this command `app-store-connect get-latest-testflight-build-number`.

**Comment by victor-heali** [comment]
any updates on this?

**Comment by priitlatt** [comment]
@martinjeret @victor-heali do you have any suggestions how to improve docs for this? Current documentation can be seen from the [here](https://github.com/codemagic-ci-cd/cli-tools/blob/master/docs/app-store-connect/get-latest-testflight-build-number.md#--pre-release-versionpre_release_version).

**Comment by martinjeret** [comment]
I would add to the part where it says 

Optional arguments for action get-latest-testflight-build-number
`--pre-release-version=PRE_RELEASE_VERSION`
Version of the build published to Testflight that identifies an iteration of the bundle. The string can only contain one to three groups of numeric characters (0-9) separated by period in the format [Major].[Minor].[Patch]. For example 3.2.46

If the optional argument PRE_RELEASE_VERSION is not set then ...

I like how default behaviour is explained in app store connect command and jtw token cache for example. 

--api-unauthorized-retries, -r=UNAUTHORIZED_REQUEST_RETRIES
Specify how many times the App Store Connect API request should be retried in case the called request fails due to an authentication error (401 Unauthorized response from the server). In case of the above authentication error, the request is retried usinga new JSON Web Token as many times until the number of retries is exhausted. If not given, the value will be checked from the environment variable APP_STORE_CONNECT_API_UNAUTHORIZED_RETRIES. **[Default: 3]**

**Comment by priitlatt** [comment]
As `--pre-release-version` flag is optional, it does not have a default value.
