### ISSUE TITLE
handle App Store Connect API key is missing header and footer in app-store-connect commands

### ISSUE THREAD

**Issue by craastad** [codemagic-ci-cd/cli-tools#138]
Sometimes users pass in a private key missing the `-----BEGIN PRIVATE KEY-----` or `-----END PRIVATE KEY-----` header or footer. In [app-store-connect](https://github.com/codemagic-ci-cd/cli-tools/blob/master/docs/app-store-connect/README.md) commands, it would be nice to handle this case: either return a helpful error message or just attempt processing the private key if these are missing.

**Comment by priitlatt** [comment]
Won't fix.
