### ISSUE TITLE
google-play CLI client does not detect or allow custom tracks

### ISSUE THREAD

**Issue by poiriermike** [codemagic-ci-cd/cli-tools#152]
I've created a custom track, which are now supported in the publishing stage of the pipeline. However, the `google-play` cli tool does not yet support the ability to detect and/or query custom tracks. 

This is problematic as publishing to a track increments the version code, but since the google-play tool doesn't detect the custom track, it cannot increment the build number, and thus the build fails due to it attempting to overwrite an existing version code.

**Comment by ankitjainOfficial** [comment]
same issue.

**Comment by priitlatt** [comment]
@poiriermike @ankitjainOfficial Support for using custom tracks is supported since [version 0.24.0](https://github.com/codemagic-ci-cd/cli-tools/releases/tag/v0.24.0).
