### ISSUE TITLE
Command for macOS UI testing

### ISSUE THREAD

**Issue by rudrankriyam** [codemagic-ci-cd/cli-tools#161]
When interacting with the UI while testing a macOS app, we get an alert for granting permission:

![Screen Shot 2021-10-31 at 4 04 56 PM](https://user-images.githubusercontent.com/30552772/139710081-c3c3133e-14a2-4191-8f97-8eb7a5269c94.png)

![Screen Shot 2021-10-31 at 4 13 38 PM](https://user-images.githubusercontent.com/30552772/139710086-2b1a568c-01c8-4f76-b8ba-c2eac141c70d.png)

It is feasible on the local machine. However, it is not possible in the remote environment without providing the relevant permissions. It'll make it a lot easier to provide an executable similar to: 

```
xcode-project mac-permission
        [--add-uitest-permission]
```

Thank you!

**Comment by priitlatt** [comment]
Thanks for reporting this. We'll look into it.

**Comment by rudrankriyam** [comment]
Closing the issue as the relevant permissions required are now present in the VMs
