### ISSUE TITLE
Document process to generate mypy stubs

### ISSUE THREAD

**Issue by artemii-yanushevskyi** [codemagic-ci-cd/cli-tools#194]
Per this [discussion](https://github.com/codemagic-ci-cd/cli-tools/pull/192#discussion_r783199184), it would be nice to document the process for generation of mypy stubs with stubgen.

**Comment by priitlatt** [comment]
More and more packages already include type hints, or have dedicated mirror-packages that define type stubs. I don't think adding documentation for this is work it any more at this point.
