### ISSUE TITLE
keychain -h does not mention option -p or --path

### ISSUE THREAD

**Issue by mmattes** [codemagic-ci-cd/cli-tools#233]
I have the cli tools version 0.27.0 on my system running `keychain -h` does not mention the -p or --path option which is mentioned here in github https://github.com/codemagic-ci-cd/cli-tools/blob/master/docs/keychain/README.md. I think it would be good for other users to add this to the `keychain -h`

**Comment by priitlatt** [comment]
@mmattes Thanks for bringing this to our attention. Sadly the arguments that apply to the whole tool (regardless of certain action) are not displayed when `tool-name --help / -h` is used. This is a limitation that applies not only to `keychain` but to all other tools, such as `app-store-connect` etc, too.

This is the default behaviour of Python's `argparse` module which is used for underlying implementation to take care of the help messages. That being said, it should be very doable to include global arguments in the tool-level help messages.
