### ISSUE TITLE
documentation link for `Profiles.get_bundle_id_resource_id` is dead

### ISSUE THREAD

**Issue by DetachHead** [codemagic-ci-cd/cli-tools#237]
https://github.com/codemagic-ci-cd/cli-tools/blob/5058be610f2a7219310037f8cbeffbf647bcb174/src/codemagic/apple/app_store_connect/provisioning/profiles.py#L122

![image](https://user-images.githubusercontent.com/57028336/171622455-d5b90c7e-06f4-47cc-a858-f8c86bbaab4f.png)

**Comment by Nytrm** [comment]
https://developer.apple.com/documentation/appstoreconnectapi/read_the_bundle_id_in_a_profile

would probably be the new one, `/profiles/{profile}/relationships/bundleId`  on line 128 needs to be changed accordingly.
to `profiles/{profile}/bundleId`

**Comment by Nytrm** [comment]
ah i see different endpoint but they removed the documentation, yet would it not be better to use the https://developer.apple.com/documentation/appstoreconnectapi/read_the_bundle_id_in_a_profile endpoint instead and remove the other one ? (or link it to the new endpoint)

**Comment by VeArnold** [comment]
Thanks for reporting; we've updated the docstring to point to the resource instead, as the other endpoint returns considerable more data, which is not required for these definitions.
