### ISSUE TITLE
Facing issue connecting with test flight via app-store-connect CLI

### ISSUE THREAD

**Issue by asudharsan** [codemagic-ci-cd/cli-tools#251]
Hi team,
I am trying to connect to test flight in app store connect using the command

```bash
app-store-connect \
    get-latest-testflight-build-number '${app_id}' \
    --issuer-id "${issuer_id}" \
    --key-id "${key_id}" \
    --private-key "${private_key}" \
    --platform=IOS \
    --pre-release-version "${app_version}"
```

But i keep running into the error below 

```
GET https://api.appstoreconnect.apple.com/v1/preReleaseVersions?limit=100&include=builds&filter%5Bapp%5D=${app_id}&filter%5Bplatform%5D=IOS&filter%5Bversion%5D=${app_version} returned 401: Authentication credentials are missing or invalid. - Provide a properly configured and signed bearer token, and make sure that it has not expired. Learn more about Generating Tokens for API Requests https://developer.apple.com/go/?id=api-generating-tokens
```

I used the same command back in May but i never faced this issue. But now I am getting this token issue which according to the link https://developer.apple.com/go/?id=api-generating-tokens is for sending CURL request but not to use with the command `app-store-connect`.

Did something change recently? Can someone help me debug this issue?

I have admin level access in app store connect in case it is needed

Thank you,
Aravind

**Comment by priitlatt** [comment]
Hi @asudharsan. Thanks for reaching out and sorry for the delayed response on our part. Could you please confirm that you're still experiencing the issue that you've described?

Authentication mechanism in `app-store-connect` internals is not changed and the JWT tokens that are discussed in the documentation you referenced are the ones that `app-store-connect` also uses. Under the hood it does the same HTTP requests as one would do using `cURL`.

The error message
```
401: Authentication credentials are missing or invalid. - Provide a properly configured and signed bearer token, and make sure that it has not expired.
```
suggests that either 
- your API key was revoked at some point in App Store Connect,
- value of environment variable `issuer_id`, `key_id` or `private_key` is not correct.

I'd suggest that you head over to https://appstoreconnect.apple.com/access/api first and check that the key with id `$key_id` is active and issuer ID matches `$issuer_id`.

Please let me know if you need further help with that.

**Comment by asudharsan** [comment]
@priitlatt Thank you reaching out. Sorry i should have updated before but the issue was I was using the arguments wrongly. I was able to correct it and issue got resolved
