### ISSUE TITLE
Create an Apple APNS key from CLI

### ISSUE THREAD

**Issue by Yahllil** [codemagic-ci-cd/cli-tools#252]
Hello,
I’m currently working on a white-label app that I want to deploy through a CI/CD.
Each version of my white-label app would have a different Firebase project for using Firebase Messaging.

As you probably know, Apple enforces each version of a white-label app to be uploaded through the client’s developer account. That means, that for using iOS Push Notification, an APNS key/certificate would need to be generated for every version of the app through the client’s developer account, and would need to be uploaded to Firebase Cloud Messaging (please see image attached).

I've seen that your App Store Connect CLI tool has an option to create and download certificates, but does not have an option to create and download keys, which are needed to be uploaded to Firebase Console in order for push notifications to work on iOS (.p8/.p12 files).

This is something every white-label app will encounter when using iOS push notifications, so I believe it is something that is worth being added to the CLI, in order to allow automation of white-label apps deployment.

What do you think?

**Generating a key through Apple's portal:**
<img width="871" alt="Screen Shot 2022-08-12 at 19 06 58" src="https://user-images.githubusercontent.com/18067403/184396975-6f5f0e69-a933-46d1-8c1f-99659f825e3d.png">

**Uploading the key to Firebase Cloud Messaging (through Firebase Console):**
<img width="953" alt="Screen Shot 2022-08-12 at 19 08 19" src="https://user-images.githubusercontent.com/18067403/184397211-0e019d85-65b6-41e2-8d1c-b4171b6c620b.png">

**Comment by Ycoi** [comment]
Unfortunately Apple doesn’t offer an API for creating and downloading APNS keys like they do for signing Certificates. Thus it’s unfortunately not possible for us to add this feature to the CLI tool.

**Comment by priitlatt** [comment]
As @Ycoi said, unfortunately it cannot be done.
