### ISSUE TITLE
Feature request: Add `get-latest-build-number` command

### ISSUE THREAD

**Issue by nilsreichardt** [codemagic-ci-cd/cli-tools#279]
## Description

There is already a `get-latest-app-store-build-number` and `get-latest-testflight-build-number` command. However, I need to get the highest build number, either from AppStore or TestFlight:

Let's look at this example:
* AppStore has build number 31.
* TestFlight has build number 30.

The value of `get-latest-build-number` would be 31.

Another case:
* AppStore has build number 30.
* TestFlight has build number 32.

The value of `get-latest-build-number` would be 32.

**Comment by priitlatt** [comment]
@nilsreichardt This is now available as part of version [0.35.0](https://github.com/codemagic-ci-cd/cli-tools/releases/tag/v0.35.0) with [`app-store-connect get-latest-build-number`](https://github.com/codemagic-ci-cd/cli-tools/blob/master/docs/app-store-connect/get-latest-build-number.md#usage).

**Comment by nilsreichardt** [comment]
Oh nice! Thanks for the quick implementation, @priitlatt 🙏
