### ISSUE TITLE
Provided value is not a valid PEM encoded private key 

### ISSUE THREAD

**Issue by matiasleyba** [codemagic-ci-cd/cli-tools#296]
Hi 👋🏻

I'm trying to configure private key in order to fetch signing files, but I always see the same error: 

```shell
app-store-connect fetch-signing-files: error: argument --private-key: Provided value is not a valid PEM encoded private key
```

I did the follow steps to config `APP_STORE_CONNECT_PRIVATE_KEY`:
- Download .p8 key file from App Store Connect 
- Open key file and copy the entire content
- Encrypt the value copied with Codemagic API, using [`/encrypt-environment-variable`](https://docs.codemagic.io/rest-api/applications/#encrypting-base64-encoded-values) enpoint
- Put Encrypted value in `APP_STORE_CONNECT_PRIVATE_KEY`

Anyone knows what I'm doing wrong ?

**Comment by priitlatt** [comment]
Hi @matiasleyba. I presume that you base64-encoded the private key before encrypting it (as per the [instructions](https://docs.codemagic.io/rest-api/applications/#encrypting-base64-encoded-values)). In this case the value of the environment variable during build is also base64 encoded and it is up to the user to base64-decode it for use. Actually setting up `APP_STORE_CONNECT_PRIVATE_KEY` and other similar environment variables manually like that is not a preferred way.

Instead it would be easier to configure App Store Connect / Apple Developer Portal integration once for your team and then reference the integration from your workflow in Yaml. This way you can use one integration for both code signing and publishing all workflows. You can read more about it from [the docs](https://docs.codemagic.io/yaml-code-signing/alternative-code-signing-methods/) under "iOS" tab.

**Comment by matiasleyba** [comment]
@priitlatt thanks for the reply! 

I did the base64-encoded but I still facing the same error, so I decided to configure through the  CodeMagic UI and then reference the values in Yaml as you mentioned, and now it's working 💪🏻 thanks!
