### ISSUE TITLE
Did not find matching provisioning profiles for code signing!

### ISSUE THREAD

**Issue by jascodes** [codemagic-ci-cd/cli-tools#311]
After re-creating my flutter ios project I am getting the below issue. Even after deleting my provision profile and cli-tools resulting in creating a new one. You can check out logs below.

```
Get Profiles for Bundle ID ***HBD
Did not find any Profiles for Bundle ID ***HBD matching specified filters: profileState=ACTIVE, profileType=IOS_APP_STORE.
Did not find any Profiles that contain Signing Certificate Apple Distribution: Glu Learning FZE (***9XG)
Found 3 Devices matching specified filters: platform=IOS, status=ENABLED.
Found 1 Signing Certificate matching specified filters: certificateType=DISTRIBUTION,IOS_DISTRIBUTION.
Get Bundle ID ***HBD
Creating new Profile: name: '***522', profile type: IOS_APP_STORE, bundle id: ***HBD, certificates: ['***9XG']
Created Profile 7[24](https://github.com/glulearning/glu_client_flutter/actions/runs/4176373388/jobs/7232640324#step:6:25)X8VZA2H

Saved Signing Certificate Apple Distribution: Glu Learning FZE (***9XG) to /Users/runner/Library/MobileDevice/Certificates/DISTRIBUTION_***9XG__a4o6pu1.p12
Saved Profile IOS_APP_STORE GLU Learning Dev ios_app_store ***522 (***A2H) to '/Users/runner/Library/MobileDevice/Provisioning Profiles/IOS_APP_STORE_***A2H_3hs3c0om.mobileprovision'
Add certificates to keychain /Users/runner/Library/codemagic-cli-tools/keychains/14-02-23_qffmwnk2.keychain-db
Searching for files matching /Users/runner/Library/MobileDevice/Certificates/*.p12
Add certificate /Users/runner/Library/MobileDevice/Certificates/DISTRIBUTION_***9XG__a4o6pu1.p12 to keychain /Users/runner/Library/codemagic-cli-tools/keychains/14-02-23_qffmwnk2.keychain-db
1 key imported.
1 certificate imported.
Configure code signing settings
Searching for files matching /Users/runner/Library/MobileDevice/Provisioning Profiles/*.mobileprovision
Searching for files matching /Users/runner/Library/MobileDevice/Provisioning Profiles/*.provisionprofile
List available code signing certificates in keychain /Users/runner/Library/codemagic-cli-tools/keychains/14-02-23_qffmwnk2.keychain-db
Searching for files matching /Users/runner/work/glu_client_flutter/glu_client_flutter/**/*.xcodeproj
Completed configuring code signing settings
Did not find matching provisioning profiles for code signing!
Generated options for exporting the project
 - Method: ad-hoc
 - Provisioning Profiles: []
 - Signing Certificate: 
 - Signing Style: manual
 - Team Id: 
Saved export options to /Users/runner/export_options.plist
```

**Comment by priitlatt** [comment]
Hi @jascodes. I understand that you're running the following commands:
- [`app-store-connect fetch-signing-files`](https://github.com/codemagic-ci-cd/cli-tools/blob/master/docs/app-store-connect/fetch-signing-files.md)
- [`keychain add-certificates`](https://github.com/codemagic-ci-cd/cli-tools/blob/master/docs/keychain/add-certificates.md)
- [`xcode-project use-profiles`](https://github.com/codemagic-ci-cd/cli-tools/blob/master/docs/xcode-project/use-profiles.md)

From the log output I can deduce that an existing Apple Distribution certificate was found and a new iOS App Store provisioning profile containing this certificate was created.

The problem appears to be that `xcode-project use-profiles` does configure this new profile for your Xcode project build targets. Sadly with the log output you've shared I'm unable to pin down the exact reason why this is happening. Usually it boils down to project's and provisioning profile bundle identifier mismatch.

For now I can suggest that you enable verbose logging for code signing setup phase by adding [`--code-signing-setup-verbose-logging`](https://github.com/codemagic-ci-cd/cli-tools/blob/master/docs/xcode-project/use-profiles.md#--code-signing-setup-verbose-logging) command line option to your `xcode-project use-profiles` invocation. This will show in great detail which bundle identifier is detected for your Xcode project targets.

**Comment by jascodes** [comment]
@priitlatt Apologies mate, My bad the issue was the when I regenerate, I forgot to open xcode and update Team ID.

Then it works.

Thanks
