### ISSUE TITLE
Firebase app distribution get latest build version is not working

### ISSUE THREAD

**Issue by Buddybetadmin** [codemagic-ci-cd/cli-tools#321]
We are trying to use the latest cli-tools firebase-app-distribution utility to fetch the latest build number from firebase using your documentations on codemagic website as well as github. 

```shell
$LATEST_BUILD_VERSION_ANDROID=$(firebase-app-distribution get-latest-build-version -p $FIREBASE_PROJECT_ID -a $Android_Firebase_App_ID_QA)
```

but we keep getting this weird error: 
`Client error. name: firebaseappdistribution  version: v1`

It seems like there is something wrong with the utility. Or we doing something wrong?

**Comment by priitlatt** [comment]
Hi @Buddybetadmin! Thanks for bringing this up. The error you mentioned originates from too old Google API client library that the tools were using. This is fixed with [version 0.40.2](https://github.com/codemagic-ci-cd/cli-tools/releases/tag/v0.40.2).
