### ISSUE TITLE
Add all environmental variables to .env file

### ISSUE THREAD

**Issue by leonid-demyanenko** [codemagic-ci-cd/cli-tools#341]
We are using approach with .evn file on out flutter. 
We need all our environmental variables to appear in .env file before build.
Currently we are copying it with a script. But sometimes issues happens when we forgot to add new variable to the copying script.

So I'm wondering if  there is a way to copy all invariable variables without mentioning each one.

**Comment by priitlatt** [comment]
Hi @leonid-demyanenko, could you share some more details on what tool and action this issue is related to? For general Codemagic support please refer to [Codemagic Github discussions](https://github.com/orgs/codemagic-ci-cd/discussions) page.
