### ISSUE TITLE
Be able to set both tags triggers at the same time as branch filtering

### ISSUE THREAD

**Issue by guplem** [codemagic-ci-cd/cli-tools#384]
Workflows Triggered Incorrectly on Tag Creation Across Multiple Branches

**Description:**
When creating tags in a repository with multiple workflows set up for different branches, both workflows are incorrectly triggered even if the tag is created in one specific branch. 
The expected behavior is for only the workflow associated with the branch where the tag is created to be triggered.
This has been discussed in the [Discussion 2264](https://github.com/orgs/codemagic-ci-cd/discussions/2264#discussioncomment-7905549).

**Steps to Reproduce:**
1. Create two workflows in a repository for an app. Each workflow should be configured for different branches (e.g., "dev" and "main").
2. Configure both workflows to be triggered by the same tag creation event, but make sure each workflow is set for its specific branch.
3. Push changes to one of the branches (e.g., "dev") and create a new tag on this branch.
4. Observe that both workflows (for "dev" and "main" branches) get triggered, despite the tag being created only in the "dev" branch.

**Expected Results:**
Only the workflow associated with the branch where the tag was created (e.g., "Dev" workflow) should be triggered.

**Actual Results:**
Both the "Production" (main branch) and "Dev" (dev branch) workflows are triggered, despite the tag creation in the "dev" branch only.

**Comment by helinanever** [comment]
Hi @guplem . I'm going to close the issue as the problem you are describing is not related to the Codemagic CLI tools. Please follow up on the discussion you linked or consider posting a feature idea in Discussions.

**Comment by guplem** [comment]
> Hi @guplem . I'm going to close the issue as the problem you are describing is not related to the Codemagic CLI tools. Please follow up on the discussion you linked or consider posting a feature idea in Discussions.

Sure, I will turn [Discussion 2264](https://github.com/orgs/codemagic-ci-cd/discussions/2264#discussioncomment-7905549) into an "idea".
