### ISSUE TITLE
Adding profile entitlements dynamically

### ISSUE THREAD

**Issue by icarusdust** [codemagic-ci-cd/cli-tools#385]
When building iOS apps, some capabilities need to be added to bundle identifiers and their associated provisioning profiles. Currently, it can be done manually either by configuring them in the Apple Developer Account or in Xcode. Maybe something similar to Fastlane `template_name `

**Comment by priitlatt** [comment]
Adding capabilities to bundle identifiers was introduced in PR #388. Is there anything else that needs to be done?

**Comment by icarusdust** [comment]
That should be it. Thanks!

**Comment by priitlatt** [comment]
Resolved by #388.
