### ISSUE TITLE
[BUG] ImportError: cannot import name 'Literal' from 'typing'

### ISSUE THREAD

**Issue by frederikstonge** [codemagic-ci-cd/cli-tools#412]
Receiving this error this morning : ImportError: cannot import name 'Literal' from 'typing'. Seems to be related to the latest release.

**Comment by priitlatt** [comment]
@frederikstonge thanks for reporting this. That'll be resolved ASAP.

**Comment by frederikstonge** [comment]
> @frederikstonge thanks for reporting this. That'll be resolved ASAP.

I think it's because Literal has been introduced in python 3.8. The documentation still says 3.7+.

**Comment by priitlatt** [comment]
Yes, you are absolutely correct. It happens only with Python 3.7.

**Comment by priitlatt** [comment]
@frederikstonge this is now fixed in [version 0.53.2](https://github.com/codemagic-ci-cd/cli-tools/releases/tag/v0.53.2). Also available from PyPI @ https://pypi.org/project/codemagic-cli-tools/0.53.2/.

I'm really sorry for this mishap.

**Comment by frederikstonge** [comment]
Thanks a lot for the quick response!
