### ISSUE TITLE
"app-store-connect fetch-signing-files --type MAC_APP_DIRECT" does not fetch new DEVELOPER_ID_APPLICATION_G2 certificates

### ISSUE THREAD

**Issue by aemelyanovff** [codemagic-ci-cd/cli-tools#414]
`app-store-connect fetch-signing-files --type MAC_APP_DIRECT` calls `GET https://api.appstoreconnect.apple.com/v1/certificates {'limit': 100, 'sort': 'displayName', 'filter[certificateType]': 'DEVELOPER_ID_APPLICATION'}`.  But newer Developer ID Application certificates created by choosing the `G2 Sub-CA` profile type don't match the filter because their type is `DEVELOPER_ID_APPLICATION_G2`.

It looks like it's impossible to use `DEVELOPER_ID_APPLICATION_G2` certificates with Codemagic.

**Comment by priitlatt** [comment]
@aemelyanovff, this is now fixed in [version 0.53.3](https://github.com/codemagic-ci-cd/cli-tools/releases/tag/v0.53.3).
