### ISSUE TITLE
Feature request: Add option to `app-store-connect fetch-signing-files` to exactly match specified bundle identifier 

### ISSUE THREAD

**Issue by Webjin** [codemagic-ci-cd/cli-tools#63]
Please consider adding a toggle to make the BUNDLE_ID matching strict, instead of wildcard, for the following card

`app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create`

In our case we have apps with bundle_ids "com.company.project" and "com.company.project.test".
When fetching provisioning profiles for the first it would also return for the second.

Suggeste solution could be a toggle for making the matching strict

`app-store-connect fetch-signing-files "$BUNDLE_ID" --match-strict --type IOS_APP_STORE --create`

**Comment by priitlatt** [comment]
It will be added once #87 gets approved and merged.

**Comment by priitlatt** [comment]
Available in [version 0.5.3](https://pypi.org/project/codemagic-cli-tools/0.5.3/).
