### ISSUE TITLE
Feature idea: get latest build number from app store connect

### ISSUE THREAD

**Issue by martinjeret** [codemagic-ci-cd/cli-tools#64]
looks like app store connect API has option to get list of builds associated with an app i.e. https://developer.apple.com/documentation/appstoreconnectapi/list_all_builds_of_an_app

maybe we can create some automatic numbering to always use latest build number +1 so people don't need to worry about versioning scripts? 

This feature idea is not about of version name

**Comment by priitlatt** [comment]
Resolved by pull request #67. Added actions
- [app-store-connect list-builds](https://github.com/codemagic-ci-cd/cli-tools/blob/master/docs/app-store-connect/list-builds.md)
- [app-store-connect get-latest-testflight-build-number](https://github.com/codemagic-ci-cd/cli-tools/blob/master/docs/app-store-connect/get-latest-testflight-build-number.md)
- [app-store-connect get-latest-app-store-build-number](https://github.com/codemagic-ci-cd/cli-tools/blob/master/docs/app-store-connect/get-latest-app-store-build-number.md)

See example usages from linked pull request description.
