### ISSUE TITLE
Feature request: Submit for review with app-store-connect

### ISSUE THREAD

**Issue by nevercode-kevin** [codemagic-ci-cd/cli-tools#65]
Extend app-store-connect to use the App Store Connect API to submit app for App Store review as described here:

https://developer.apple.com/documentation/appstoreconnectapi/app_store_version_submissions

This would reduce manual interaction with App Store Connect UI which would be advantageous for production workflows.

**Comment by fbartho** [comment]
Related feature: automatically click the button to "Prepare a new release" -- currently we have to set the marketing version in the AppStore UI manually before the build pops out of CI

**Comment by priitlatt** [comment]
Very bare bones support for the initial request comes with #85. More user friendly support needs further discussion and probably more in-depth approach since it depends on other App Store publishing aspectes.
