### ISSUE TITLE
Invalid provisioning profile /xxx/xxx.mobileprovision

### ISSUE THREAD

**Issue by manggalarefactory** [codemagic-ci-cd/cli-tools#83]
Hello i have an issue when command `xcode-project use-profiles`

![Screen Shot 2021-03-16 at 14 34 20](https://user-images.githubusercontent.com/80512656/111278387-0dbcd080-866c-11eb-8258-bca4a59a57d2.png)

any idea what's going on? I tried in my local laptop and had same issue.

**Comment by BondarenkoStas** [comment]
Hi @manggalarefactory, the most frequent reason is that the profile is not a profile at all. Are you sure it's a `.mobileprovision` profile that you added? What I mean is that sometimes users add a `.cer` certificate or `.zip` archive instead of a profile.

**Comment by manggalarefactory** [comment]
i build again

![image](https://user-images.githubusercontent.com/80512656/111294444-e9b5bb00-867c-11eb-99e7-ba31ff772083.png)

![image](https://user-images.githubusercontent.com/80512656/111294461-efab9c00-867c-11eb-821c-76ca4ebac4ff.png)

they are same file but can be read. I don't have any idea.
@BondarenkoStas

**Comment by albemala** [comment]
I was having the same issue. Changing this line in the building script from:

`echo ${FCI_PROVISIONING_PROFILE} | base64 --decode > $PROFILE_PATH`

to:

`echo ${FCI_PROVISIONING_PROFILE} | base64 --decode > "$PROFILE_PATH"`

(I added the `""` around `$PROFILE_PATH`) fixed the problem. Hope this helps other people.
